[package]
name = "blas-sys"
version = "0.6.6"
license = "Apache-2.0/MIT"
authors = [
    "Andrew Straw <strawman@astraw.com>",
    "Corey Richardson <corey@octayn.net>",
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
    "bluss",
]
description = "The package provides bindings to the Basic Linear Algebra Subprograms."
documentation = "https://docs.rs/blas-sys"
homepage = "https://github.com/stainless-steel/blas-sys"
repository = "https://github.com/stainless-steel/blas-sys"
categories = ["external-ffi-bindings", "science"]
keywords = ["linear-algebra"]

[features]
default = ["openblas"]

accelerate = ["accelerate-src"]
netlib = ["netlib-src"]
openblas = ["openblas-src"]

[dependencies]
libc = "0.2"

[dependencies.accelerate-src]
version = "0.3"
optional = true

[dependencies.netlib-src]
version = "0.7"
optional = true

[dependencies.openblas-src]
version = "0.5"
optional = true
